### ISSUE TITLE
EVENT_REWARD_QUEST + ACTION_TALK

### ISSUE THREAD

**Issue by Nqsty** [SunstriderProject/Sunstrider-Issues#73]
When you turn in the quest (10447), he *says* a line and then *yells* the creature_text one:
Tooki *says*: The threat be over! Nasty be savin' us all!
Tooki *yells*: The threat be over! Nasty be savin' us all!

The first line should not happen.
[Tooki's creature_text](http://www.sunstrider.cf/suntools/external/creature_text/index.php?entry=18447)

**Comment by kelno** [comment]
Actually the SmartAI is sending the first one (which by the way has the type 12 when the maximum existing is 7, so it defaults to "say", another problem here).
And the second line is done by the script in quest_end_scripts. This redundancy is probably caused by the batch import of smartAI scripts on creature not having any AI yet. No general fixes there, we just have to remove the quest_end_script by hand.

**Comment by kelno** [comment]
The following creatures have both quest end scripts and smartAI :
entry - quest
836	3364
1373	308
1416	7642
1449	349
1557	410
2080	930
2080	931
2080	997
2289	619
2688	652
2911	943
3142	806
3594	3118
4709	1191
5888	1521
5901	5158
7007	1103
7804	3321
18447	10447
21311	10526
22231	10813
22293	10850
22924	10988

**Comment by kelno** [comment]
The following creature have both quest start scripts and smartAI :
entry - quest
2391	2480
2921	778
2986	1149
3584	945
3692	994
3692	995
3693	986
6176	1713
6546	1957
6546	4961
7207	2608
7750	2701
7766	434
7790	2755
7802	2765
7802	3625
7804	3321
7853	2843
9117	4321
18471	9962
18471	9967
18471	9970
18471	9972
18471	9973
18471	9977
21797	10639
22373	10879
23905	11198

**Comment by kelno** [comment]
I guess I'l just remove the quest_*_scripts
